import SystemCard from "./SystemCard";

const SYSTEMS = [
  {
    id: "combat",
    number: "06",
    title: "Combat & Damage Model",
    emoji: "⚔️",
    phase: "Phase 1",
    phaseColor: "bg-red-500/20 text-red-400",
    priority: "🔴 CRITICAL",
    priorityColor: "bg-red-500/10 text-red-400",
    stars: 5,
    accentColor: "from-red-600 to-rose-600",
    borderColor: "border-red-900/40",
    description: "DF-inspired detailed combat with material interactions, 8 damage types, body-part targeting, and class-specific abilities with screen-juice feedback systems.",
    features: [
      "8 damage types: Impact, Pierce, Fire, Ice, Electric, Void, Arcane, Psychic",
      "Body-part targeting: Shell, Core, Eye, Propulsion, Mana Channel",
      "Material resistance system — rock-paper-scissors depth",
      "4 abilities per class + ultimate with synergy design",
      "Screen shake, damage numbers, slow-mo killing blow",
      "Chain reactions: electric hits 2+ targets, fire spreads",
      "Hit sparks match material: crystal shatter, metal clang, void ripple",
    ],
    compareRows: [
      { aspect: "Combat", before: "Basic HP reduction", after: "Material-based, body-part targeting, elemental" },
      { aspect: "Depth", before: "Attack = damage", after: "Rock-paper-scissors + DF body system" },
      { aspect: "Abilities", before: "Basic or few", after: "4 per class + ultimate, class synergy" },
      { aspect: "Feedback", before: "Minimal", after: "Screen shake, slowmo, sparks, numbers" },
    ],
    verdict: "ESSENTIAL — Combat is what players DO most. This makes every fight tactical.",
  },
  {
    id: "physics",
    number: "04",
    title: "Physics & Environment Simulation",
    emoji: "⚡",
    phase: "Phase 2",
    phaseColor: "bg-amber-500/20 text-amber-400",
    priority: "🟡 IMPORTANT",
    priorityColor: "bg-amber-500/10 text-amber-400",
    stars: 4,
    accentColor: "from-amber-600 to-orange-600",
    borderColor: "border-amber-900/40",
    description: "DF-level environmental simulation: fluid dynamics, fire propagation, destruction chains, dynamic lighting with raycasting shadows, and 12+ properties per tile.",
    features: [
      "Fluid sim: water flows down elevation via cellular automata",
      "Lava flows slowly, ignites flammable tiles, water + lava = obsidian",
      "Fire propagation with wind direction, smoke vision reduction",
      "Destruction engine: explosions, rubble, chain reactions",
      "Crystal tile near mana explosion = mana chain reaction",
      "2D raycasting shadow system — dark tiles grant +20% evasion",
      "Each tile: material, hardness, flammability, conductivity, resonance",
    ],
    compareRows: [
      { aspect: "Environment", before: "Static background", after: "Living, reactive, destructible world" },
      { aspect: "Fluids", before: "None", after: "Water, lava, poison, mana streams" },
      { aspect: "Fire", before: "None or cosmetic", after: "Full propagation with tactical impact" },
      { aspect: "Lighting", before: "Flat/uniform", after: "Dynamic shadows = stealth + tactics" },
    ],
    verdict: "HIGH IMPROVEMENT — Battles reshape the map itself. Emergent chaos like DF.",
  },
  {
    id: "crafting",
    number: "07",
    title: "Crafting & Upgrade Economy",
    emoji: "🔧",
    phase: "Phase 4",
    phaseColor: "bg-blue-500/20 text-blue-400",
    priority: "🟢 ENHANCING",
    priorityColor: "bg-blue-500/10 text-blue-400",
    stars: 4,
    accentColor: "from-blue-600 to-indigo-600",
    borderColor: "border-blue-900/40",
    description: "DF-inspired resource chain feeding into CTF strategy. 6 resource types, in-match crafting at base anvils, team shared economy, and cross-match meta progression.",
    features: [
      "6 resources: Mana Shards, Crystal Ore, Void Essence, Ancient Gears, Ember Dust, Frost Core",
      "Crafting recipes: Shell Reinforcement, Speed Conduit, Trap Kit, Healing Fountain",
      "Legendary recipe: Soul of Annihilation (30s craft, interruptible!)",
      "Contested resource points in neutral zones (risk vs. reward)",
      "Team shared pool + individual pool with vote system",
      "Resource denial strategy: destroy enemy nodes",
      "Cross-match: skill trees (3 branches, 20 nodes each), artifact collection",
    ],
    compareRows: [
      { aspect: "Economy", before: "None or basic pickups", after: "Full resource chain with crafting" },
      { aspect: "Strategy", before: "Just combat + movement", after: "Resource control + denial + crafting" },
      { aspect: "Progression", before: "Per-match only", after: "Cross-match skill trees, artifacts, mutations" },
      { aspect: "Cooperation", before: "Parallel play", after: "Shared economy, voting, trading" },
    ],
    verdict: "STRONG IMPROVEMENT — Players who don't fight can still contribute via resource control.",
  },
  {
    id: "social",
    number: "08",
    title: "Social & Faction Diplomacy",
    emoji: "🤝",
    phase: "Phase 3",
    phaseColor: "bg-emerald-500/20 text-emerald-400",
    priority: "🟢 ENHANCING",
    priorityColor: "bg-emerald-500/10 text-emerald-400",
    stars: 4,
    accentColor: "from-emerald-600 to-teal-600",
    borderColor: "border-emerald-900/40",
    description: "DF-style social web with persistent relationships, dynamic rivalries, and 4 factions competing in seasonal wars. Relationships have real gameplay impact.",
    features: [
      "RIVAL: +10% damage vs rival, -10% defense, red line on minimap",
      "NEMESIS: skull icon, dedicated kill tracking, special announcements",
      "BONDED_ALLY: +15% stats when within 5 tiles of bonded partner",
      "FEARED: -10% stats when feared soul is visible (must defeat to remove)",
      "MENTOR system: +20% XP for student near mentor",
      "4 Factions: Radiant Collective, Void Syndicate, Crystal Accord, Ember Legion",
      "Faction wars: seasonal leaderboard CTF tournaments with unique abilities",
    ],
    compareRows: [
      { aspect: "Social", before: "Anonymous per-match", after: "Persistent relationships with gameplay impact" },
      { aspect: "Narrative", before: "None", after: "Emergent rivalries, mentorships, alliances" },
      { aspect: "Metagame", before: "Match-to-match", after: "Faction wars, seasonal arcs, community events" },
      { aspect: "Replayability", before: "Mechanic-only", after: "Social reasons to keep playing" },
    ],
    verdict: "SIGNIFICANT IMPROVEMENT — DF's legendary stories come from relationships.",
  },
  {
    id: "lore",
    number: "09",
    title: "Procedural Lore & History",
    emoji: "📜",
    phase: "Phase 3",
    phaseColor: "bg-emerald-500/20 text-emerald-400",
    priority: "🟢 ENHANCING",
    priorityColor: "bg-emerald-500/10 text-emerald-400",
    stars: 5,
    accentColor: "from-violet-600 to-purple-600",
    borderColor: "border-violet-900/40",
    description: "Auto-generated deep-simulation-style chronicles after every match. The world builds its own history, maps remember events, and player actions create legends.",
    features: [
      "Auto-generated Chronicle Entry after every match",
      'Template: "In the Battle of {map_name}, {winner} claimed victory…"',
      "World History Timeline with 'Ages' based on faction dominance",
      "Maps remember history: tiles show past events",
      "Procedural name generator: 'Zyx the Volatile', 'Kael Ironshell'",
      "Earned titles: 'Flag Thief' (50 captures), 'Worldbreaker' (1000 tiles destroyed)",
      "Library of Echoes: in-game scrollable timeline with filters",
    ],
    compareRows: [
      { aspect: "Lore", before: "None", after: "Auto-generated, personalized, persistent" },
      { aspect: "Identity", before: "Username only", after: "Name + earned titles + chronicles" },
      { aspect: "World feel", before: "Static", after: "Living history that players CREATE" },
      { aspect: "Content", before: "Manual dev work", after: "Infinite procedural lore" },
    ],
    verdict: "MAJOR IMPROVEMENT — This is what makes DF legendary. Players share stories.",
  },
  {
    id: "weather",
    number: "11",
    title: "Weather & Seasonal Cycle",
    emoji: "🌦️",
    phase: "Phase 3",
    phaseColor: "bg-emerald-500/20 text-emerald-400",
    priority: "🟢 ENHANCING",
    priorityColor: "bg-emerald-500/10 text-emerald-400",
    stars: 3,
    accentColor: "from-cyan-600 to-blue-600",
    borderColor: "border-cyan-900/40",
    description: "Dynamic weather changes tactics every 2-5 minutes. Seasonal meta evolution across real time with faction bonuses. From CLEAR to VOID_ECLIPSE (rare, terrifying).",
    features: [
      "RAIN: Fire -50%, electric chains +1 target, puddles form",
      "STORM: Random lightning strikes highest-elevation souls",
      "FOG: Minimap disabled, stealth +40%, 30% visibility",
      "MANA_RAIN: Mana regen x3, ability cooldowns -50%",
      "VOID_ECLIPSE: 10% visibility, void x2, bioluminescence — 30s duration",
      "CRYSTAL_SHOWER: Crystals rain down, creating temporary walls",
      "4 seasons: Light, Shadow, Balance, War — monthly meta shifts",
    ],
    compareRows: [
      { aspect: "Weather", before: "None or cosmetic", after: "Tactical, gameplay-changing weather" },
      { aspect: "Seasonal", before: "None", after: "Year-round meta evolution" },
      { aspect: "Strategy", before: "Static optimal build", after: "Must adapt to conditions" },
      { aspect: "Visual variety", before: "Same every match", after: "Dramatically different atmospheres" },
    ],
    verdict: "STRONG IMPROVEMENT — Seasons keep the meta fresh year-round.",
  },
  {
    id: "endgame",
    number: "20",
    title: "Endgame & Prestige Loop",
    emoji: "🏆",
    phase: "Phase 4",
    phaseColor: "bg-blue-500/20 text-blue-400",
    priority: "🟢 ENHANCING",
    priorityColor: "bg-blue-500/10 text-blue-400",
    stars: 5,
    accentColor: "from-amber-500 to-yellow-600",
    borderColor: "border-amber-900/40",
    description: "Infinite prestige system, seasonal ranked ladder, cosmetic-only battle pass, achievement system with 50+ unlocks, and daily/weekly quest loops.",
    features: [
      "Prestige: 10 levels, reset to 1 keeping cosmetics, gain prestige border",
      "Each prestige: unique soul skin + title + mutation unlock",
      "Seasonal 3-month ranked: Bronze → Champion with exclusive cosmetics",
      "Achievements: Combat, CTF, Social, Crafting, Exploration, Lore, Prestige",
      '"The Eternal" achievement: Prestige 10 any class',
      "Daily quests (3/day) + Weekly quests (3/week) with XP rewards",
      "Champion rank: unique animated soul skin + title",
    ],
    compareRows: [
      { aspect: "Endgame", before: "None — players finish and leave", after: "Infinite prestige, seasons, achievements" },
      { aspect: "Retention", before: "Short-term", after: "Long-term with daily/weekly hooks" },
      { aspect: "Monetization", before: "Unknown", after: "Ethical cosmetic-only model" },
      { aspect: "Community", before: "Passive", after: "Active (seasons, events, faction wars)" },
    ],
    verdict: "CRITICAL FOR LONGEVITY — Even the best game dies without endgame loops.",
  },
  {
    id: "modding",
    number: "16",
    title: "Modding Support",
    emoji: "🛠️",
    phase: "Phase 5",
    phaseColor: "bg-purple-500/20 text-purple-400",
    priority: "🔵 POST-LAUNCH",
    priorityColor: "bg-purple-500/10 text-purple-400",
    stars: 5,
    accentColor: "from-purple-600 to-violet-600",
    borderColor: "border-purple-900/40",
    description: "Fully data-driven architecture enabling community mods: new classes, biomes, game modes, abilities scripted in LUA, and total conversion support.",
    features: [
      "All game data in JSON/YAML — nothing hardcoded",
      "Moddable: souls, abilities (LUA), biomes, weather, crafting, maps, AI trees",
      "In-game map editor: tile-by-tile or brush-based",
      "Soul Creator: visual stat editor with balance scoring",
      "Ability Scripter: template-based with LUA override",
      "Steam Workshop / itch.io integration",
      "Sandbox execution, checksum validation, vanilla/modded matchmaking queues",
    ],
    compareRows: [
      { aspect: "Moddability", before: "Hardcoded systems", after: "Fully data-driven + scripted mods" },
      { aspect: "Content", before: "Dev only", after: "Community-generated infinite content" },
      { aspect: "Longevity", before: "Depends on updates", after: "Community keeps game alive for years" },
    ],
    verdict: "LONG-TERM CRITICAL — deep-simulation thrives on community. So will Bit-Soul.",
  },
];

const SystemsGrid = () => {
  return (
    <section className="py-20 px-6 bg-[#080812]">
      <div className="max-w-6xl mx-auto">
        <div className="text-center mb-12">
          <div className="text-xs text-violet-400 tracking-widest uppercase mb-2">Systems Deep Dive</div>
          <h2 className="text-4xl md:text-5xl font-black text-white mb-3">All 20 Systems</h2>
          <p className="text-white/50 max-w-xl mx-auto">Click "Explore" on any system to reveal features, compare before/after, and read the verdict</p>
        </div>

        <div className="grid md:grid-cols-2 gap-4">
          {SYSTEMS.map((sys) => (
            <SystemCard key={sys.id} {...sys} />
          ))}
        </div>
      </div>
    </section>
  );
};

export default SystemsGrid;
